spring:
  application:
    name: Cards

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://127.0.0.1:8080/issuer

logging:
  level:
    org.springframework.security: trace
